apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yomi-argoCD
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YomiPounds/yomi-repo.git
    targetRevision: HEAD
    path: yom
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
